# 50 Numpy Methods or Attributes

In [1]:
import numpy as np

In [6]:
#1. Adding Two Arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
add = arr1+arr2
add

array([ 7,  9, 11, 13, 15])

In [7]:
#2. Subtracting Two Arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
Sub = arr2-arr1
Sub

array([5, 5, 5, 5, 5])

In [9]:
#3. Multiplying Two Arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
Mul = arr1*arr2
Mul

array([ 6, 14, 24, 36, 50])

In [10]:
#4. Deviding Two Arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
Dev = arr2/arr1
Dev

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [11]:
#5. Sorting Array
arr = np.array([43,1,57,88,13])
sortedArray = np.sort(arr)
sortedArray

array([ 1, 13, 43, 57, 88])

In [12]:
#6. Where()
studentMarks = np.array([73,33,67,11,34,56,88,53,100,5])
print(np.where(studentMarks <= 40,"Fail","Pass"))

['Pass' 'Fail' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail']


In [13]:
#7. Unique()
uniqueness = np.unique(arr1)
uniqueness

array([1, 2, 3, 4, 5])

In [14]:
#8. arange()
newArray = np.arange(1,10)
newArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#9. Concatination() through rows
TwoDarr1 = np.arange(1,10).reshape(3,3)
TwoDarr2 = np.arange(11,20).reshape(3,3)
print(np.concatenate((TwoDarr1,TwoDarr2),axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [17]:
#10. Concatination() through Column
TwoDarr1 = np.arange(1,10).reshape(3,3)
TwoDarr2 = np.arange(11,20).reshape(3,3)
print(np.concatenate((TwoDarr1,TwoDarr2),axis=1))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [18]:
#11. Splitting through rows
arr = np.array([1,2,3,4,5])
print(np.split(arr1,[1,3],axis=0)) 

[array([1]), array([2, 3]), array([4, 5])]


In [19]:
#12. Splitting through column
arr2 = np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25]])
print(np.split(arr2,[1,3],axis=1))

[array([[ 1],
       [11],
       [21]]), array([[ 2,  3],
       [12, 13],
       [22, 23]]), array([[ 4,  5],
       [14, 15],
       [24, 25]])]


In [22]:
#13. Dimensions of Array

arr0 = np.array(23)          #0 Dimention Array
arr1 = np.array([1,2,3,4,5])    #1 Dimention Array 
arr2 = np.array([[1,2,3],[4,5,6]])          #2 Dimention Array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])    #3 Dimention Array
arrMul = np.array([1,2,3,4,5], ndmin = 5) #we use "ndmin" for multiple Dimention Array

In [23]:
#14."ndim"
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arrMul.ndim)

0
1
2
3
5


In [24]:
#15. "shape"
print(arr0.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arrMul.shape)

()
(5,)
(2, 3)
(2, 2, 3)
(1, 1, 1, 1, 5)


In [27]:
#16. changing Type
l = (1,2,3,4,5)
arr = np.array(l, dtype = float)
print(arr)

[1. 2. 3. 4. 5.]


In [29]:
#17. np.zeros()     return array of 0
arr = np.zeros((3,4))  # 3 rows and 4 column
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
#18. np.ones()      return array of 1
arr = np.ones((3,4))  # 3 rows and 4 column
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
#19. # np.empty()     return random numbers depending upon the state of the memory.
arr = np.empty((3,4))
print (arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#20. np.eye()    returns identity matrix of given dimensions
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#21. Identity
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#22. arange()   similar as range function but it returns ndarray
arr = np.arange(15)
print (arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [36]:
#23. Checking Numpy Version
#Checking NumPy Version
print(np.__version__)

1.18.1


In [37]:
#24. convertng a list into a one-dimensional NumPy array
l = (1,2,3,4,5)
arr = np.array(l)
print(arr)

[1 2 3 4 5]


In [39]:
#25. Comparison
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print("\nComparison of two arrays: \n",arr1<=arr2)


Comparison of two arrays: 
 [ True  True  True  True  True]


In [40]:
#26. randn()
data = np.random.randn(5,4)
data

array([[ 4.26004429e-01,  1.44185599e-01, -1.38611953e+00,
        -3.85563072e-01],
       [-1.54555857e-01, -4.22076240e-01,  2.40160256e+00,
        -9.53266322e-01],
       [ 6.56515206e-01, -5.45754332e-01, -1.49016081e-01,
        -1.33171563e+00],
       [ 1.94328657e+00,  1.47298023e+00,  4.75942480e-01,
        -5.90853698e-01],
       [-4.90886865e-03, -3.87601214e-01,  1.03810624e+00,
        -3.55983707e-04]])

In [42]:
#27. reshape()
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [43]:
#28. Fancy Indexing
arr = np.arange(32).reshape(8,4)
print(arr[[1,4],[0,2]])

[ 4 18]


In [44]:
#29. Sum()
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [45]:
#30. Sum ()  (Boolean Function)      Counts how many values are True
chances = np.array([True,False,False,True,True,True,False,True,False,False])
print(np.sum(chances))  

5


In [46]:
#31. all ()  (Boolean Function)      Checks if one or more values are True
chances = np.array([True,False,False,True,True,True,False,True,False,False])
print(np.all(chances))  

False


In [47]:
#32. any ()  (Boolean Function)      Checks if every value is true
chances = np.array([True,False,False,True,True,True,False,True,False,False])
print(np.any(chances))  

True


In [48]:
#33. mean()
arr = np.array([1,8,3,77,15])
print(np.mean(arr)) 

20.8


In [49]:
#34. cumsum()
arr = np.array([1,8,3,77,15])
print(np.cumsum(arr))   

[  1   9  12  89 104]


In [50]:
#35. cumrod()
arr = np.array([1,8,3,77,15])
print(np.cumprod(arr))  

[    1     8    24  1848 27720]


In [51]:
#36. Save()
np.save("Saving Numpy array",arr1)     #Saving a single array in file
arr1 = np.array([1,2,3,4,5])

In [53]:
#37. load()
print(np.load("Saving Numpy array.npy"))      #Loading From File

[1 2 3 4 5]


In [58]:
#38. savez()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = np.array([11,12,13,14,15])
np.savez("Saving Multiple Numpy arrays",arr1,"\n",arr2,"\n",arr3)    #Saving Multiple Arrays


In [59]:
#39. dot()       Dot product of two matrixes
x = np.arange(1,10).reshape(3,3)
y = np.arange(11,20).reshape(3,3)
print(x.dot(y))        

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [60]:
#40. diag()       Diagonal of matrix
x = np.arange(1,10).reshape(3,3)
y = np.arange(11,20).reshape(3,3)
print(np.diag(x))      

[1 5 9]


In [61]:
#41. trace()     #Compute the sum of diagonal
x = np.arange(1,10).reshape(3,3)
y = np.arange(11,20).reshape(3,3)
print(np.trace(y))     #Compute the sum of diagonal

45


In [62]:
#42. transpose()        #Transpose of matrix
x = np.arange(1,10).reshape(3,3)
y = np.arange(11,20).reshape(3,3)
print(np.transpose(y)) 

[[11 14 17]
 [12 15 18]
 [13 16 19]]


In [63]:
#43. random.normal()
x = np.random.normal(size=(3,3))
print(x)

[[-0.04939059 -1.43354776  1.48206544]
 [-0.45504751 -0.24000649  1.6561142 ]
 [ 0.6138586   0.94846805  0.82605195]]


In [64]:
#44. random.uniform()
y = np.random.uniform(size=(2,2))
print(y)

[[0.63063961 0.21766736]
 [0.3939889  0.14337857]]


In [65]:
#45. ravel()
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ravel()) 

[1 2 3 4 5 6 7 8 9]


In [66]:
#46. flatten()
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.flatten())

[1 2 3 4 5 6 7 8 9]


In [67]:
#47. Repeat
arr = np.array([1,2,3,4,5])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [68]:
#48. Tiles
arr = np.array([1,2,3,4,5])
print(np.tile(arr,3))

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [76]:
#49. astype()
l = np.array([1,2,3])
print(l.astype(float))

[1. 2. 3.]


In [88]:
arr = np.array([[4,1,8],[9,6,2],[2,5,4]])
determinant = np.linalg.det(arr)
int(determinant)

288